### ISSUE TITLE
Running queries

### ISSUE THREAD

**Issue by AlyssaByrnes** [nandhp/python-imdb#5]
Hello! I am new to using python to query data. I downloaded the files and followed the instructions to create imdb.zip and imdb.zip.idx. 
Now how do I use a file, say "example.py" to actually run queries? When I tried just running "python example.py", I got an error.  
Sorry for my ignorance! Any help is appreciated!

![error](https://cloud.githubusercontent.com/assets/11397510/13332439/9d0954ca-dbc7-11e5-90aa-95e4cfc29916.PNG)

Alyssa Byrnes

**Comment by nandhp** [comment]
Hello,

It is trying to use the external program `gzip` to access the compressed index, and it is not able to find it in your `PATH`. (Using the external program is much faster than the GzipFile Python module.) I am a little surprised that this is failing for search, though, given that the index file would have been created the same way. I am not sure where to recommend getting a Windows version of Gzip, but you could start by checking http://www.gzip.org/
