### ISSUE TITLE
ASCII-related error when using example.py

### ISSUE THREAD

**Issue by PeterBennink** [nandhp/python-imdb#7]
When I use the example.py file, I get an error after about 25 movies:

```
Traceback (most recent call last):
  File "example.py", line 13, in <module>
    print u'%s has rating %s/10 (%d ratings)' % (title, r.score, r.nratings)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
```

I have looked on the internet, and I know I should do something with encode('utf-8'), however, I can't seem to find the place in the code where I should add this.

**Comment by nandhp** [comment]
Thank you for reporting this. It was a fairly subtle problem -- the score is actually a Unicode string, which was causing the obvious solutions to your original problem to fail with a new ASCII *decode* error as it tried to upgrade everything *back* to Unicode. That took quite a while to figure out, but I've pushed a fix. Thanks again.

**Comment by PeterBennink** [comment]
Thank you so much, for the fast response, and for the solution!
